name: hci
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - pip=24.0=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - catkin-pkg==1.0.0
      - certifi==2024.6.2
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - distro==1.9.0
      - docutils==0.21.2
      - easydict==1.13
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - ffmpeg==1.4
      - filelock==3.14.0
      - flatbuffers==24.3.25
      - flit==3.9.0
      - flit-core==3.9.0
      - fonttools==4.53.0
      - freetype-py==2.4.0
      - fsspec==2024.5.0
      - future==1.0.0
      - idna==3.7
      - imageio==2.34.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.4
      - ipympl==0.9.4
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.5
      - iso8601==2.1.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.1
      - jinja2==3.1.4
      - jpeg4py==0.1.4
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - keyboard==0.13.5
      - kiwisolver==1.4.5
      - lxml==5.2.2
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mediapipe==0.10.15
      - ml-dtypes==0.5.0
      - modern-robotics==1.1.1
      - mpmath==1.3.0
      - mr-urdf-loader==0.0.10
      - nest-asyncio==1.6.0
      - networkx==2.2
      - numpy==1.23.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.16.1
      - onnx-graphsurgeon==0.5.0
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.2
      - prompt-toolkit==3.0.45
      - protobuf==4.25.5
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pycollada==0.6
      - pycparser==2.22
      - pyglet==2.0.15
      - pygments==2.18.0
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - pyrender==0.1.45
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - requests==2.32.3
      - rospkg==1.5.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - serial==0.0.97
      - six==1.16.0
      - sounddevice==0.5.0
      - stack-data==0.6.3
      - sympy==1.12.1
      - tensorrt==10.0.1
      - tensorrt-dispatch==10.0.1
      - tensorrt-lean==10.0.1
      - thread==2.0.3
      - tomli-w==1.0.0
      - torch==2.3.0
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - trimesh==4.4.0
      - triton==2.3.0
      - typing-extensions==4.12.1
      - tzdata==2024.1
      - ultralytics==8.2.28
      - ultralytics-thop==0.2.6
      - urdfpy==0.0.22
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.13
      - zipp==3.19.1
prefix: /home/aloha/anaconda3/envs/hci
